name: Build

on:
  repository_dispatch:
    types: [build_release]


jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: set python 
        uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9' 
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GH_SOURCE }}
          token: ${{ secrets.GH_TOKEN }} # `GH_TOKEN` is a secret that contains your PAT
          path: _source
          ref: main
      - name: move file
        run:  mv -f $GITHUB_WORKSPACE/_source/*  $GITHUB_WORKSPACE 
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.18'
        # Cache node modules to accelerate
      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Use npm cache
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm build
      - name: Install dependencies for cn
        run: cd $GITHUB_WORKSPACE/cn/ && npm ci
      - name: build for cn
        run: cd $GITHUB_WORKSPACE/cn/ && npm run build
      - name: set search all
        run: cd $GITHUB_WORKSPACE/ && python $GITHUB_WORKSPACE/search.py 
      - name: mv file
        run: mkdir $GITHUB_WORKSPACE/public/cn/ && mv -f $GITHUB_WORKSPACE/cn/public/*  $GITHUB_WORKSPACE/public/cn/ && cd $GITHUB_WORKSPACE/
      - name: clean
        run: mkdir ~/_the_next/ && mv -f $GITHUB_WORKSPACE/public/* ~/_the_next/ && rm -rf $GITHUB_WORKSPACE/ && mkdir $GITHUB_WORKSPACE 
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          ref: web_page
      - name: clean pre version
        run:  rm -rf $GITHUB_WORKSPACE/public && mkdir  $GITHUB_WORKSPACE/public/
      - name: copy
        run: cp -r -f ~/_the_next/* $GITHUB_WORKSPACE/public 
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true      
      - name: Commit 
        run: |
          git pull
          git config --global user.email "117530179+czqu@users.noreply.github.com"
          git config --global user.name "czqu"
          git add .
          git commit -m "build new html" 
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          github_token: $TOKEN
          branch: web_page
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public/

      
