name: Build

on:
  repository_dispatch:
    types: [build]


jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release
        uses: actions/checkout@v3
        with:
          ref: web_page
      - name: clean pre version
        run:  rm -rf $GITHUB_WORKSPACE/public && mkdir  $GITHUB_WORKSPACE/public/
      - name: Checkout pre
        uses: actions/checkout@v3
        with:
          path: pre
          ref: web_page_pre
      - name: copy
        run: cp -r -f $GITHUB_WORKSPACE/pre/public/* $GITHUB_WORKSPACE/public 
      - name: clean
        run:  rm -rf $GITHUB_WORKSPACE/pre 
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true      
      - name: Commit 
        run: |
          git pull
          git config --global user.email "117530179+czqu@users.noreply.github.com"
          git config --global user.name "czqu"
          git add .
          git commit -m "build new html" 
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          github_token: $TOKEN
          branch: web_page
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public/

      
