name: Build

on:
  repository_dispatch:
    types: [build_pre]


jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GH_SOURCE }}
          token: ${{ secrets.GH_TOKEN }} # `GH_TOKEN` is a secret that contains your PAT
          path: _source
          ref: main
      - name: move file
        run:  mv -f $GITHUB_WORKSPACE/_source/*  $GITHUB_WORKSPACE 
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17'
        # Cache node modules to accelerate
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: build
        run: yarn build
      - name: ready to build cn
        runL cd ./cn
      - name: Install dependencies for cn
        run: yarn install --prefer-offline --frozen-lockfile
      - name: build for cn
        run: yarn build
      - name: mv file
        run: mv -f $GITHUB_WORKSPACE/cn/public/*  $GITHUB_WORKSPACE/public/cn/
      - name: clean
        run: mkdir ~/_the_next/ && mv -f $GITHUB_WORKSPACE/public/* ~/_the_next/ && rm -rf $GITHUB_WORKSPACE/ && mkdir $GITHUB_WORKSPACE 
      - name: Checkout pre
        uses: actions/checkout@v3
        with:
          ref: web_page_pre
      - name: clean pre version
        run:  rm -rf $GITHUB_WORKSPACE/public && mkdir  $GITHUB_WORKSPACE/public/
      - name: copy
        run: cp -r -f ~/_the_next/* $GITHUB_WORKSPACE/public 
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true      
      - name: Commit 
        run: |
          git pull
          git config --global user.email "117530179+czqu@users.noreply.github.com"
          git config --global user.name "czqu"
          git add .
          git commit -m "build new html" 
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          github_token: $TOKEN
          branch: web_page_pre
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public/

      
